# Generated by Django 5.2.3 on 2025-06-30 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='El nombre del ejercicio.', max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField(db_index=True, help_text='La fecha en que se realizó el entrenamiento.')),
            ],
            options={
                'ordering': ['-workout_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(help_text='Número de series realizadas.')),
                ('reps', models.PositiveIntegerField(help_text='Número de repeticiones por serie.')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Peso levantado en kilogramos.', max_digits=6)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_entries', to='api.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.workout')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('workout', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(help_text='Ejercicios realizados en esta sesión de entrenamiento.', related_name='workouts', through='api.WorkoutEntry', to='api.exercise'),
        ),
    ]
