# Fichero de configuración principal para Gym Performance Analyzer
# Aquí puedes ajustar todos los parámetros sin tocar el código.

# --- Parámetros Generales del Análisis ---
analysis_params:
  use_3d_analysis: True  # Poner en 'False' para usar el pipeline 2D antiguo
  generate_debug_video: True
  debug_mode: True

# --- Parámetros del Ejercicio: Sentadilla (Squat) ---
squat_params:
  # Umbrales para el conteo de repeticiones (en grados)
  high_thresh: 140.0
  low_thresh: 80.0
  peak_prominence: 10.0
  peak_distance: 15
  
  # Umbral para el fallo de profundidad (si el ángulo mínimo no baja de esto, es un fallo)
  depth_fail_thresh: 90.0

# --- Parámetros de la GUI ---
# (Se podrían añadir en el futuro, como colores, temas, etc.)