# Generated by Django 4.2.23 on 2025-07-01 10:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_workouts", models.PositiveIntegerField(default=0)),
                ("total_exercises", models.PositiveIntegerField(default=0)),
                ("total_sets", models.PositiveIntegerField(default=0)),
                ("total_reps", models.PositiveIntegerField(default=0)),
                (
                    "total_workout_time",
                    models.PositiveIntegerField(
                        default=0, help_text="Tiempo total de entrenamiento en minutos"
                    ),
                ),
                (
                    "average_workout_duration",
                    models.FloatField(
                        default=0.0,
                        help_text="Duración promedio de entrenamiento en minutos",
                    ),
                ),
                ("total_videos_analyzed", models.PositiveIntegerField(default=0)),
                (
                    "average_technique_score",
                    models.FloatField(
                        default=0.0, help_text="Puntuación promedio de técnica"
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Racha actual de días consecutivos entrenando",
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Racha más larga de días consecutivos"
                    ),
                ),
                (
                    "last_workout_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha del último entrenamiento",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadísticas de Usuario",
                "verbose_name_plural": "Estadísticas de Usuario",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Fecha de nacimiento", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("O", "Otro"),
                            ("N", "Prefiero no decir"),
                        ],
                        help_text="Género",
                        max_length=1,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="Número de teléfono", max_length=20
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Altura en centímetros",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso en kilogramos",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Principiante (0-6 meses)"),
                            ("intermediate", "Intermedio (6 meses - 2 años)"),
                            ("advanced", "Avanzado (2+ años)"),
                            ("expert", "Experto (5+ años)"),
                        ],
                        default="beginner",
                        help_text="Nivel de experiencia en el gimnasio",
                        max_length=20,
                    ),
                ),
                (
                    "primary_goal",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Pérdida de peso"),
                            ("muscle_gain", "Ganancia muscular"),
                            ("strength", "Aumento de fuerza"),
                            ("endurance", "Resistencia"),
                            ("general_fitness", "Fitness general"),
                            ("rehabilitation", "Rehabilitación"),
                        ],
                        default="general_fitness",
                        help_text="Objetivo principal de entrenamiento",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_units",
                    models.CharField(
                        choices=[("metric", "Métrico"), ("imperial", "Imperial")],
                        default="metric",
                        help_text="Sistema de unidades preferido",
                        max_length=10,
                    ),
                ),
                (
                    "enable_notifications",
                    models.BooleanField(
                        default=True, help_text="Habilitar notificaciones push"
                    ),
                ),
                (
                    "enable_video_analysis",
                    models.BooleanField(
                        default=True, help_text="Habilitar análisis automático de vídeo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_workout_duration",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Duración preferida del entrenamiento en minutos",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "preferred_rest_time",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Tiempo de descanso preferido entre series en segundos",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "preferred_muscle_groups",
                    models.JSONField(
                        default=list,
                        help_text="Grupos musculares de preferencia del usuario",
                    ),
                ),
                (
                    "avoided_exercises",
                    models.JSONField(
                        default=list,
                        help_text="IDs de ejercicios que el usuario prefiere evitar",
                    ),
                ),
                (
                    "available_days",
                    models.JSONField(
                        default=list,
                        help_text="Días de la semana disponibles para entrenar (1-7)",
                    ),
                ),
                (
                    "preferred_workout_time",
                    models.TimeField(
                        blank=True, help_text="Hora preferida para entrenar", null=True
                    ),
                ),
                (
                    "analysis_sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                        ],
                        default="medium",
                        help_text="Sensibilidad del análisis de técnica",
                        max_length=20,
                    ),
                ),
                (
                    "auto_save_videos",
                    models.BooleanField(
                        default=False,
                        help_text="Guardar automáticamente los vídeos analizados",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencias de Usuario",
                "verbose_name_plural": "Preferencias de Usuario",
            },
        ),
    ]
